# Site settings
email: doctorants.actifs@gmail.com
baseurl: ""
# paginate: 1
# paginate_path: "/blog/page-:num"
google_analytics: 

# SEO settings
title: Club Doctorants Actifs
part-title: Doctorants Actifs
club: DOC-AC
description: Club Doctorants Actifs Rouen France
url: "https://doctorants-actifs.github.io"
twitter_username: 
default_img: 
lang: fr  # the default langauge.

first_published: 2017
number_members: 33  # number if subscribed members.
logo: "images/8hrb.png"
logopdf: "images/8-new.pdf"
admin: "images/admin.jpeg"
# Profile settings
name: 
profile_img: 
profile: 
social:
  github: https://github.com/doctorants-actifs

owner:
  name: Club Doctorants Actifs # or company name
  email: doctorants.actifs@gmail.com
  url: https://doctorants-actifs.github.io
# Names
accueil-text:
  fr: Accueil
  en: Home
proposition-text:
  fr: Proposition?
  en: Proposition?
a-propos-text:
  fr: À propos
  en: About
s-inscrire-text:
  fr: S'inscrire
  en: Subscribe
archive-text:
  fr: Événements 
  en: Events
se-desinscrire-text:
  fr: Se déscinscrire
  en: Unsubscribe
back-to-posts-text:
  fr: Retourner aux posts
  en: Back to posts
read-post-text:
  fr: Lire le post
  en: Read post
# Links
index:
  fr:
  en: index-en
proposition:
  fr: https://goo.gl/forms/4zN1hc7aJSmvleN22
  en: https://goo.gl/forms/QdTXv6QUfVvbFUpQ2
a-propos:
  fr: /a-propos/
  en: /a-propos-en/
s-inscrire:
  fr: https://goo.gl/forms/Xmmf2N6cSxS2RCsG3
  en: https://goo.gl/forms/5aEmnSNFfCpilGe22
se-desinscrire:
  fr: https://goo.gl/forms/88ing0GM0hndb8Ti2
  en: https://goo.gl/forms/nCEFGXhMAUIa7lbi2
archive:
  fr: /archive/
  en: /archive-en/
date-trans:
  January:
    en: January
    fr: Janvier
  February:
    en: February
    fr: Février
  March:
    en: March
    fr: Mars
  April:
    en: April
    fr: Avril
  May:
    en: May
    fr: Mai
  June:
    en: June
    fr: Juin
  July:
    en: July
    fr: Juillet
  August:
    en: August
    fr: Août
  September:
    en: September
    fr: Septembre
  October:
    en: October
    fr: Octobre
  November:
    en: November
    fr: Novembre
  December:
    en: December
    fr: Décembre
savoir_plus:
  fr: En savoir +
  en: Know +
comment-it:
  fr: Laisser un avis
  en: Comment it
# Build settings
exclude: ["_screenshots", "Gemfile", "Gemfile.lock", "LICENSE.txt", "README.md"]
include: ['_pages', '.htaccess']
markdown: kramdown
# permalink: /:year/:month/:day/:title/
permalink: /:year-:month-:day-:title.html

defaults:
  - scope:
      path: _pages
    values:
      layout: page
      #permalink: /:slug/ # dunna work. See github.com/jekyll/jekyll/issues/2280
  - scope:
      path: _posts
    values:
      layout: post
  - scope:
      path: _drafts
    values:
      layout: post
future: true  # display future posts (as upcoming news)
# Sass
sass:
  style: compressed

# Gems
gems: [jekyll-paginate, jekyll-sitemap,   octopress-autoprefixer] # ,
